[project]
name = "autofx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "backtesting>=0.6.5",
    "matplotlib>=3.10.8",
    "metatrader5>=5.0.5509",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "pyarrow>=23.0.0",
    "python-dotenv>=1.2.1",
    "pytz>=2025.2",
    "scikit-optimize>=0.10.2",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
